# Generated by Django 2.1.2 on 2018-11-07 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pmanager', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Initi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mub_name', models.CharField(max_length=250)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmanager.Leaders')),
            ],
        ),
        migrations.CreateModel(
            name='MainStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=250)),
                ('ratio', models.IntegerField(default=0)),
                ('end_date', models.DateField()),
                ('progress_num', models.IntegerField(default=0)),
                ('info', models.TextField()),
                ('mub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Initi')),
            ],
        ),
        migrations.CreateModel(
            name='MdaAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mda_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_ar', models.CharField(max_length=250)),
                ('week_no', models.CharField(max_length=250)),
                ('is_read', models.BooleanField(default=False)),
                ('mub_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Initi')),
            ],
        ),
        migrations.CreateModel(
            name='Risks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(max_length=500)),
                ('owner_risk', models.CharField(max_length=250)),
                ('probability', models.CharField(max_length=250)),
                ('influence', models.CharField(max_length=250)),
                ('plan', models.CharField(max_length=250)),
                ('mub_risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Initi')),
            ],
        ),
        migrations.CreateModel(
            name='Supports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.CharField(max_length=500)),
                ('mub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Initi')),
            ],
        ),
        migrations.AddField(
            model_name='mainstage',
            name='week_ar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Reports'),
        ),
        migrations.AddField(
            model_name='goals',
            name='mub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Initi'),
        ),
    ]
