# Generated by Django 2.1.2 on 2018-11-07 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(max_length=500)),
                ('owner', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('info', models.TextField()),
                ('mub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Initi')),
                ('week_ar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Reports')),
            ],
        ),
    ]
