# Generated by Django 2.1.2 on 2018-11-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0003_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='report',
        ),
        migrations.AddField(
            model_name='reports',
            name='comment',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reports',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
