# Generated by Django 2.1.2 on 2018-11-10 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0005_auto_20181108_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('grade', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reports',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='is_read',
        ),
        migrations.AddField(
            model_name='comment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Reports'),
        ),
    ]
