# Generated by Django 2.1.2 on 2018-11-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0006_auto_20181110_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstage',
            name='final_rate',
            field=models.IntegerField(default=0),
        ),
    ]
